"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

# Function to determine if the current number 

def even_valued(n):
    if n % 2 == 0:
        return n
    else:
        return 0

# Function to create the Fibonacci Sequence

def fib_sequence():
    prev = 1
    curr = 2
    next_term = None
    even_sum = 0
    
    while curr < 4000000:
        even_sum += even_valued(curr)
        next_term = prev + curr
        prev = curr
        curr = next_term

    return even_sum

# Main function

sum = fib_sequence()
print(f"The sum of the even-valued terms bellow 4 million of the fibonacci sequence is: {sum}")
